"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { filterTools, filterWorkflows, searchTools, searchWorkflows } from "../filter";
import type { ToolItem, WorkflowItem } from "../types";
export function ToolBrowser({ items }: { items: ToolItem[] }) { const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [free, setFree] = useState(false); const filtered = useMemo(() => filterTools(searchTools(items, query), { category, free: free ? "true" : "" }), [items, query, category, free]); return <><Search value={query} onChange={setQuery} placeholder="Tool 이름이나 용도를 검색하세요" /><div className="mt-4 flex flex-wrap gap-2"><Select value={category} onChange={setCategory} label="전체 카테고리" options={[...new Set(items.map((item) => `${item.category}|${item.categoryLabel}`))].map((item) => { const [value, label] = item.split("|"); return { value, label }; })} /><label className="flex items-center gap-2 border border-zinc-800 px-3 py-2 text-sm text-zinc-400"><input type="checkbox" checked={free} onChange={(event) => setFree(event.target.checked)} /> 무료 플랜</label></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <Link href={`/app/tools/${item.slug}`} key={item.id} className="border border-zinc-800 bg-zinc-950/70 p-5 hover:border-cyan-400/40"><Badge>{item.categoryLabel}</Badge><h2 className="mt-4 text-lg font-medium">{item.name}</h2><p className="mt-2 line-clamp-3 text-sm text-zinc-400">{item.description}</p><p className="mt-4 text-xs text-zinc-500">{item.pricingLabel} · API {item.hasApi ? "지원" : "없음"} · {item.difficultyLabel}</p></Link>)}</div>{!filtered.length && <Empty text="조건에 맞는 Tool이 없습니다." />}</>; }
export function WorkflowBrowser({ items }: { items: WorkflowItem[] }) { const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [difficulty, setDifficulty] = useState(""); const filtered = useMemo(() => filterWorkflows(searchWorkflows(items, query), { category, difficulty }), [items, query, category, difficulty]); return <><Search value={query} onChange={setQuery} placeholder="Workflow 이름이나 목표를 검색하세요" /><div className="mt-4 flex flex-wrap gap-2"><Select value={category} onChange={setCategory} label="전체 카테고리" options={[...new Set(items.map((item) => `${item.category}|${item.categoryLabel}`))].map((item) => { const [value, label] = item.split("|"); return { value, label }; })} /><Select value={difficulty} onChange={setDifficulty} label="전체 난이도" options={[{ value: "beginner", label: "쉬움" }, { value: "intermediate", label: "보통" }, { value: "advanced", label: "어려움" }]} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <Link href={`/app/workflows/templates/${item.slug}`} key={item.id} className="border border-zinc-800 bg-zinc-950/70 p-5 hover:border-cyan-400/40"><Badge>{item.categoryLabel}</Badge><h2 className="mt-4 text-lg font-medium">{item.title}</h2><p className="mt-2 line-clamp-2 text-sm text-zinc-400">{item.summary}</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-zinc-500"><span>{item.difficultyLabel}</span><span>{item.setupTimeLabel}</span><span>{item.stepCount} Steps</span></div><p className="mt-3 text-xs text-cyan-300">{item.primaryTools.join(" · ")}</p></Link>)}</div>{!filtered.length && <Empty text="조건에 맞는 Workflow가 없습니다." />}</>; }
function Search({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block"><span className="sr-only">검색</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="w-full border border-zinc-800 bg-zinc-950 px-4 py-3 text-sm text-zinc-100 outline-none placeholder:text-zinc-600 focus:border-cyan-400/50" /></label>; }
function Select({ value, onChange, label, options }: { value: string; onChange: (value: string) => void; label: string; options: { value: string; label: string }[] }) { return <select value={value} onChange={(event) => onChange(event.target.value)} aria-label={label} className="border border-zinc-800 bg-zinc-950 px-3 py-2 text-sm text-zinc-400"><option value="">{label}</option>{options.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select>; }
function Badge({ children }: { children: React.ReactNode }) { return <span className="text-xs text-cyan-300">{children}</span>; }
function Empty({ text }: { text: string }) { return <p className="mt-8 border border-zinc-800 p-6 text-sm text-zinc-500">{text}<br />검색어나 필터를 변경해보세요.</p>; }
