import { describe, expect, it } from "vitest";
import { buildPackage } from "../package-builder/builder";
import { importPackage, checkCompatibility, previewImportedPackage, restoredProjectStatus } from "./installer";
import { createRequirementSnapshot } from "../requirements/snapshot";
import { generateArchitectureCandidates } from "../architecture/candidates";
import { generateBuildPlan } from "../planner/generator";
import { resolveRequiredConnectors } from "../connectors/resolver";
import { createCredentialReferences } from "../credentials/references";
function sample() { const r = createRequirementSnapshot("Create a support assistant", { automation_level: "AUTO", budget_range: "unknown", current_tools: [] }); const c = generateArchitectureCandidates(r.requirement, {}); const a = c.candidates[0].architecture; const connectors = resolveRequiredConnectors(r.requirement, a); return buildPackage({ projectId: "p1", title: "Support", goal: r.requirement.goalOriginal, author: { name: "Owner" }, snapshot: { ...r, architecture: a, architectureCandidates: c, connectors, credentialReferences: createCredentialReferences(connectors), buildPlan: generateBuildPlan({ requirement: r.requirement, architecture: a, intelligence: { buildScore: 1, automation: 1, consent: 0, manual: 0, expert: 0, unsupported: 0, estimatedBuildMinutes: 1, estimatedSetupMinutes: 1, estimatedMonthlyCostCents: 0, difficulty: "easy", riskScore: 1, confidence: 1, requiredAccounts: [], userActions: [], summary: "" } }) } as never }); }
describe("BPS installer", () => { it("imports and restores snapshots without secrets", () => { const pkg = importPackage(sample().archive, { providers: ["openai", "supabase"], connectors: ["openai", "supabase"], hosting: ["supabase"] }); expect(pkg.validation.valid).toBe(true); expect(pkg.restoredSnapshot.architecture).toBeTruthy(); expect(JSON.stringify(pkg.restoredSnapshot)).not.toContain("test-secret-value"); expect(previewImportedPackage(pkg).credentials).toBeGreaterThan(0); expect(restoredProjectStatus(pkg)).toMatchObject({ restoreStatus: "SETUP_REQUIRED", executionStarted: false, credentialsRestored: false, verificationRestoredAsEvidence: false }); }); it("rejects tampered and incompatible packages", () => { const built = sample(); const corrupted = new Uint8Array(built.archive); corrupted[corrupted.length - 1] ^= 1; expect(() => importPackage(corrupted)).toThrow(); expect(checkCompatibility(built.manifest, { providers: ["other"] }).compatible).toBe(false); }); });
