import { createHash } from "node:crypto";
import { gunzipSync } from "node:zlib";
import type { PackageManifest } from "@/features/package-builder/types";
import type { CompatibilityResult, ImportedPackage, InstallPreview } from "./types";

const text = (value: Buffer) => value.toString("utf8").replace(/\0+$/, "");
function parseManifest(source: string): PackageManifest { const result: Record<string, unknown> = {}; for (const line of source.split("\n")) { const index = line.indexOf(":"); if (index < 1) continue; const key = line.slice(0, index).trim(); const raw = line.slice(index + 1).trim(); try { result[key] = JSON.parse(raw); } catch { result[key] = raw; } } return result as unknown as PackageManifest; }
function parseTar(input: Uint8Array) { const data = gunzipSync(Buffer.from(input)); const files: Record<string, string> = {}; let offset = 0; while (offset + 512 <= data.length) { const header = data.subarray(offset, offset + 512); if (header.every((byte) => byte === 0)) break; const name = text(header.subarray(0, 100)); const size = Number.parseInt(text(header.subarray(124, 136)).trim() || "0", 8); if (!name || !Number.isFinite(size) || size < 0 || size > 20_000_000) throw new Error("PACKAGE_ENTRY_INVALID"); files[name] = text(data.subarray(offset + 512, offset + 512 + size)); offset += 512 + Math.ceil(size / 512) * 512; } return files; }
const json = <T>(files: Record<string, string>, path: string) => { try { return JSON.parse(files[path]) as T; } catch { return undefined; } };
export function checkCompatibility(manifest: PackageManifest, options: { buildFlowVersion?: string; runtimeVersion?: string; providers?: string[]; connectors?: string[]; hosting?: string[] } = {}): CompatibilityResult { const errors: string[] = []; if (!manifest.compatibility?.minBuildFlowVersion || !manifest.compatibility.minRuntime) errors.push("COMPATIBILITY_MISSING"); if (options.providers && manifest.compatibility.providers.some((item) => !options.providers?.includes(item))) errors.push("PROVIDER_UNSUPPORTED"); if (options.connectors && manifest.compatibility.connectors.some((item) => !options.connectors?.includes(item))) errors.push("CONNECTOR_UNSUPPORTED"); if (options.hosting && !manifest.compatibility.hosting.some((item) => options.hosting?.includes(item))) errors.push("HOSTING_UNSUPPORTED"); if (manifest.dependency?.providers.some((item) => options.providers && !options.providers.includes(item))) errors.push("DEPENDENCY_UNRESOLVED"); return { compatible: errors.length === 0, errors }; }
export function importPackage(input: Uint8Array, options: Parameters<typeof checkCompatibility>[1] = {}): ImportedPackage { let files: Record<string, string>; try { files = parseTar(input); } catch (error) { throw new Error(error instanceof Error ? error.message : "PACKAGE_CORRUPTED"); } if (!files["package.yaml"]) throw new Error("MANIFEST_MISSING"); const manifest = parseManifest(files["package.yaml"]); const artifacts = Object.entries(files).filter(([path]) => path !== "package.yaml" && path !== "integrity.yaml").map(([path, content]) => ({ path, type: "config", content, checksum: createHash("sha256").update(content).digest("hex") })); const errors: string[] = []; if (!manifest.id || !manifest.version || !manifest.author || !manifest.compatibility || !manifest.dependency) errors.push("MANIFEST_INVALID"); if (!/^\d+\.\d+\.\d+$/.test(manifest.version ?? "")) errors.push("VERSION_INVALID"); const integrity = files["integrity.yaml"] ?? ""; for (const line of integrity.split("\n")) { const index = line.indexOf(":"); if (index < 1) continue; const path = line.slice(0, index); const checksum = line.slice(index + 1).trim(); if (!files[path] || createHash("sha256").update(files[path]).digest("hex") !== checksum) errors.push("CHECKSUM_MISMATCH"); } const snapshot = json<Record<string, unknown>>(files, "docs/requirement-snapshot.json"); const architecture = json<Record<string, unknown>>(files, "architecture/architecture-snapshot.json"); const candidates = json<Record<string, unknown>>(files, "architecture/architecture-candidates.json"); const connectors = json<Array<Record<string, unknown>>>(files, "connectors/definitions.json") ?? []; const credentialReferences = json<Array<Record<string, unknown>>>(files, "credentials/definitions.json") ?? []; const buildPlan = json<Record<string, unknown>>(files, "build-plan/build-plan.json"); const verification = json<Record<string, unknown>>(files, "verification/rules.json"); if (!snapshot || !architecture || !buildPlan || !verification) errors.push("SNAPSHOT_OR_ARTIFACT_MISSING"); const compatibility = checkCompatibility(manifest, options); errors.push(...compatibility.errors); const credentialRequirements = credentialReferences.map((item) => ({ providerId: String(item.providerId ?? ""), definitionId: String(item.definitionId ?? ""), required: true, rotation: "runtime-managed", expiration: "runtime-managed" })); const restoredSnapshot = { requirement: snapshot, architecture, architectureCandidates: candidates, selectedArchitectureSnapshot: architecture, connectors, credentialReferences, buildPlan, testSuite: verification, package: { id: manifest.id, version: manifest.version } }; return { manifest, files, artifacts, compatibility, validation: { valid: errors.length === 0, errors }, credentialRequirements, restoredSnapshot }; }

export function restoredProjectStatus(pkg: ImportedPackage) {
  return {
    restoreStatus: "SETUP_REQUIRED" as const,
    executionStarted: false,
    credentialsRestored: false,
    verificationRestoredAsEvidence: false,
    reason: pkg.credentialRequirements.length
      ? "CREDENTIAL_AND_VERIFICATION_REQUIRED"
      : "VERIFICATION_REQUIRED",
  };
}
export function previewImportedPackage(pkg: ImportedPackage): InstallPreview { const tasks = (pkg.restoredSnapshot.buildPlan as { tasks?: Array<{ action?: string }> } | undefined)?.tasks ?? []; const automation = tasks.length ? Math.round(tasks.filter((task) => task.action === "AUTO").length / tasks.length * 100) : 0; return { packageName: pkg.manifest.displayName, version: pkg.manifest.version, author: pkg.manifest.author.name, dependencies: [...(pkg.manifest.dependency?.packages ?? []), ...(pkg.manifest.dependency?.providers ?? [])], credentials: pkg.credentialRequirements.length, connectors: (pkg.restoredSnapshot.connectors as unknown[] | undefined)?.length ?? 0, automation, estimatedMinutes: 0, estimatedCostCents: 0, validation: pkg.validation.errors, compatible: pkg.compatibility.compatible }; }
