"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { buildPackage, previewPackage } from "./builder";
import type { RequirementSnapshot } from "@/features/requirements/types";

async function projectForUser(projectId: string) { const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { data } = await supabase.from("projects").select("id,title,goal,goal_constraints").eq("id", projectId).eq("user_id", user.id).maybeSingle(); return data ? { supabase, user, project: data } : null; }
function input(access: NonNullable<Awaited<ReturnType<typeof projectForUser>>>, projectId: string, snapshot: RequirementSnapshot) { return { projectId, title: access.project.title, goal: access.project.goal ?? "", snapshot, author: { name: access.user.user_metadata?.full_name || access.user.email || "BuildFlow User", id: access.user.id } }; }
export async function previewProjectPackage(projectId: string) { const access = await projectForUser(projectId); if (!access) return { ok: false as const, error: "PROJECT_NOT_FOUND" }; const snapshot = ((access.project.goal_constraints ?? {}) as Record<string, unknown>).requirement_snapshot as RequirementSnapshot | undefined; if (!snapshot?.requirement || !snapshot.architecture || !snapshot.buildPlan) return { ok: false as const, error: "PACKAGE_INPUT_INCOMPLETE" }; return { ok: true as const, preview: previewPackage(input(access, projectId, snapshot)) }; }
export async function exportProjectPackage(projectId: string) { const access = await projectForUser(projectId); if (!access) return { ok: false as const, error: "PROJECT_NOT_FOUND" }; const snapshot = ((access.project.goal_constraints ?? {}) as Record<string, unknown>).requirement_snapshot as RequirementSnapshot | undefined; if (!snapshot?.requirement || !snapshot.architecture || !snapshot.buildPlan) return { ok: false as const, error: "PACKAGE_INPUT_INCOMPLETE" }; const built = buildPackage(input(access, projectId, snapshot)); if (!built.validation.valid) return { ok: false as const, error: "PACKAGE_VALIDATION_FAILED", validation: built.validation }; revalidatePath(`/app/projects/${projectId}`); return { ok: true as const, fileName: `${built.manifest.name}-${built.manifest.version}.bfpkg`, content: Buffer.from(built.archive).toString("base64"), size: built.estimatedSize }; }
