import { createHash } from "node:crypto";
import { gzipSync } from "node:zlib";
import type { RequirementSnapshot } from "@/features/requirements/types";
import type { BuiltPackage, PackageArtifact, PackageBuilderInput, PackageManifest, PackagePreview, PackageValidation } from "./types";

const json = (value: unknown) => JSON.stringify(value, null, 2) + "\n";
const sha256 = (value: string) => createHash("sha256").update(value).digest("hex");
const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "buildflow-package";
const yamlScalar = (value: unknown) => typeof value === "string" ? JSON.stringify(value) : JSON.stringify(value);
function archiveFiles(files: Record<string, string>) { const blocks: Buffer[] = []; for (const [name, content] of Object.entries(files)) { const body = Buffer.from(content); const header = Buffer.alloc(512); header.write(name, 0, 100, "utf8"); header.write("0000644\0", 100, 8, "ascii"); header.write("0000000\0", 108, 8, "ascii"); header.write("0000000\0", 116, 8, "ascii"); header.write(body.length.toString(8).padStart(11, "0") + "\0", 124, 12, "ascii"); header.write("00000000000\0", 136, 12, "ascii"); header[156] = 48; header.write("ustar\0", 257, 6, "ascii"); header.write("00", 263, 2, "ascii"); header.fill(" ", 148, 156); let checksum = 0; for (const byte of header) checksum += byte; header.write(checksum.toString(8).padStart(6, "0") + "\0 ", 148, 8, "ascii"); blocks.push(header, body, Buffer.alloc((512 - (body.length % 512)) % 512)); } blocks.push(Buffer.alloc(1024)); return gzipSync(Buffer.concat(blocks)); }
function manifestYaml(manifest: PackageManifest) { return ["id", "name", "displayName", "description", "version", "author", "license", "category", "tags", "visibility", "createdAt", "updatedAt", "buildflowVersion", "packageVersion", "compatibility", "dependency"].map((key) => `${key}: ${yamlScalar(manifest[key as keyof PackageManifest])}`).join("\n") + "\n"; }
function safe(value: unknown): unknown { if (Array.isArray(value)) return value.map(safe); if (!value || typeof value !== "object") return value; return Object.fromEntries(Object.entries(value).filter(([key]) => !/(secret|token|password|api.?key|private.?key|response.?body|raw.?credential)/i.test(key)).map(([key, child]) => [key, safe(child)])); }
function artifact(path: string, type: string, value: unknown): PackageArtifact { const content = typeof value === "string" ? value.endsWith("\n") ? value : value + "\n" : json(safe(value)); return { path, type, content, checksum: sha256(content) }; }
function makeManifest(input: PackageBuilderInput): PackageManifest { const now = input.now ?? new Date().toISOString(); const providers = input.snapshot.connectors.map((item) => item.providerId); return { id: `com.buildflow.project.${slug(input.projectId)}`, name: slug(input.title), displayName: input.title, description: input.snapshot.requirement.businessGoal || input.goal, version: "1.0.0", author: input.author, license: "UNLICENSED", category: input.snapshot.requirement.category, tags: [input.snapshot.requirement.goalType], visibility: "private", createdAt: now, updatedAt: now, buildflowVersion: input.buildFlowVersion ?? "0.1.0", packageVersion: "bps-1.0", compatibility: { minRuntime: "1.0.0", minBuildFlowVersion: input.buildFlowVersion ?? "0.1.0", providers, connectors: providers, regions: ["global"], hosting: ["self-hosted", "supabase"] }, dependency: { packages: [], blueprints: [], connectors: providers, providers } }; }
function buildArtifacts(input: PackageBuilderInput): PackageArtifact[] { const s = input.snapshot; return [artifact("README.md", "document", `# ${input.title}\n\nBuildFlow Package generated from Project ${input.projectId}.\n`), artifact("docs/requirement-snapshot.json", "document", s.requirement), artifact("architecture/architecture-snapshot.json", "config", s.architecture), artifact("architecture/architecture-candidates.json", "config", s.architectureCandidates ?? { version: "none", candidates: [] }), artifact("connectors/definitions.json", "config", s.connectors), artifact("credentials/definitions.json", "config", s.credentialReferences), artifact("build-plan/build-plan.json", "config", s.buildPlan), artifact("verification/rules.json", "config", s.testSuite), artifact("manifest/requirement.json", "config", { constraints: s.constraints, consents: s.consents, clarification: s.clarificationSummary, buildPreference: s.buildPreference })]; }
export function validatePackage(manifest: PackageManifest, artifacts: PackageArtifact[], snapshot?: Partial<RequirementSnapshot>): PackageValidation { const errors: string[] = []; const missing: string[] = []; if (!manifest.id || !manifest.version || !manifest.author?.name || !manifest.category || !manifest.compatibility || !manifest.dependency) errors.push("MANIFEST_REQUIRED_FIELD_MISSING"); if (!/^\d+\.\d+\.\d+$/.test(manifest.version)) errors.push("VERSION_INVALID"); for (const path of ["README.md", "docs/requirement-snapshot.json", "architecture/architecture-snapshot.json", "connectors/definitions.json", "credentials/definitions.json", "build-plan/build-plan.json", "verification/rules.json"]) if (!artifacts.some((item) => item.path === path)) missing.push(path); if (!snapshot?.architecture || !snapshot.requirement) errors.push("SNAPSHOT_INCOMPLETE"); if (missing.length) errors.push("ARTIFACT_MISSING"); return { valid: errors.length === 0, errors, missing }; }
export function buildPackage(input: PackageBuilderInput): BuiltPackage { const manifest = makeManifest(input); const artifacts = buildArtifacts(input); const manifestContent = manifestYaml(manifest); const files: Record<string, string> = Object.fromEntries([["package.yaml", manifestContent], ...artifacts.map((item) => [item.path, item.content]), ["integrity.yaml", artifacts.map((item) => `${item.path}: ${item.checksum}`).join("\n") + "\n"]]); const validation = validatePackage(manifest, artifacts, input.snapshot); const estimatedSize = Object.values(files).reduce<number>((total, content) => total + Buffer.byteLength(content), 0); const archive = archiveFiles(files); return { manifest, artifacts, missing: validation.missing, estimatedSize, validation, files, archive }; }
export function previewPackage(input: PackageBuilderInput): PackagePreview { const built = buildPackage(input); return { manifest: built.manifest, artifacts: built.artifacts, missing: built.missing, estimatedSize: built.estimatedSize, validation: built.validation }; }
