const labels: Record<string, string> = { AUTO: "자동 구축", PARTIAL: "부분 자동", CONSENT_REQUIRED: "동의 필요", MANUAL: "수동 작업", EXPERT: "전문가 필요", UNSUPPORTED: "지원 범위 외" };

type Snapshot = { requirement?: { expectedOutput?: string; category?: string }; clarificationQuestions?: { question: string; required: boolean }[]; clarificationSummary?: { completeness: number; buildReadiness: number }; conversation?: { state: string; missing: string[]; summary: { nextQuestion: { question: string } | null } }; constraints?: { level: string; reason: string }[]; capabilities?: { id: string; label: string; level: string; reason: string }[]; capabilitySummary?: { automation: number; consent: number; manual: number; expert: number; unsupported: number }; architecture?: { summary: string; components: { id: string; name: string; category: string }[]; connections: { from: string; to: string; label: string }[] }; buildIntelligence?: { buildScore: number; automation: number; estimatedBuildMinutes: number; estimatedSetupMinutes: number; estimatedMonthlyCostCents: number; difficulty: string; riskScore: number; confidence: number; requiredAccounts: string[]; userActions: string[]; summary: string } };

export function RequirementSummary({ snapshot }: { snapshot: Snapshot | undefined }) {
  if (!snapshot?.requirement) return null;
  const pending = snapshot.clarificationQuestions?.filter((question) => question.required) ?? [];
  const summary = snapshot.capabilitySummary;
  const clarification = snapshot.clarificationSummary;
  const conversation = snapshot.conversation;
  return <section className="mt-8 border border-cyan-400/20 bg-cyan-400/5 p-6">
    <p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Requirement Snapshot</p>
    <h2 className="mt-3 text-lg font-medium">현재까지 이해한 내용</h2>
    <p className="mt-2 text-sm text-zinc-300">{snapshot.requirement.expectedOutput ?? "AI 시스템"} · {snapshot.requirement.category ?? "확인 필요"}</p>
    {conversation && <div className="mt-5 border border-zinc-800 bg-zinc-950/40 p-4"><p className="text-xs uppercase tracking-[0.15em] text-zinc-500">Conversation State</p><p className="mt-2 text-sm text-cyan-200">{conversation.state}</p>{conversation.summary.nextQuestion && <p className="mt-2 text-sm text-zinc-400">다음 질문: {conversation.summary.nextQuestion.question}</p>}</div>}
    {clarification && <div className="mt-5 grid grid-cols-2 gap-3"><Metric label="정보 완성도" value={`${clarification.completeness}%`} /><Metric label="Build Readiness" value={`${clarification.buildReadiness}%`} /></div>}
    {summary && <div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Automation" value={`${summary.automation}%`} /><Metric label="Consent" value={`${summary.consent}건`} /><Metric label="Manual" value={`${summary.manual}건`} /><Metric label="Expert" value={`${summary.expert}건`} /><Metric label="Unsupported" value={`${summary.unsupported}건`} /></div>}
    {snapshot.buildIntelligence && <BuildReceipt intelligence={snapshot.buildIntelligence} />}
    {snapshot.architecture && <ArchitectureSummary architecture={snapshot.architecture} />}
    {pending.length > 0 && <div className="mt-5"><h3 className="text-sm font-medium text-zinc-300">우선 확인할 질문</h3><ul className="mt-2 grid gap-2 text-sm text-zinc-500">{pending.map((question) => <li key={question.question}>• {question.question}</li>)}</ul></div>}
    <div className="mt-5"><h3 className="text-sm font-medium text-zinc-300">구축 가능 범위</h3><div className="mt-2 grid gap-2 text-sm text-zinc-500">{snapshot.capabilities?.map((item) => <p key={item.id}><span className="mr-2 text-cyan-300">{labels[item.level] ?? item.level}</span>{item.label} — {item.reason}</p>) ?? snapshot.constraints?.map((item) => <p key={item.reason}>{item.reason}</p>)}</div></div>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-zinc-800 bg-zinc-950/50 p-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-lg font-medium text-zinc-100">{value}</p></div>; }
function BuildReceipt({ intelligence }: { intelligence: NonNullable<Snapshot["buildIntelligence"]> }) { return <div className="mt-5 border border-cyan-300/30 bg-zinc-950/60 p-5"><p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Build Receipt</p><p className="mt-3 text-sm text-zinc-300">{intelligence.summary}</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Build Score" value={`${intelligence.buildScore}점`} /><Metric label="예상 시간" value={`${intelligence.estimatedBuildMinutes + intelligence.estimatedSetupMinutes}분`} /><Metric label="예상 월 비용" value={`${Math.round(intelligence.estimatedMonthlyCostCents / 100).toLocaleString("ko-KR")}원`} /><Metric label="Confidence" value={`${intelligence.confidence}%`} /></div><div className="mt-4 grid gap-2 text-sm text-zinc-400"><p>난이도: {intelligence.difficulty} · 위험도: {intelligence.riskScore}점</p>{intelligence.requiredAccounts.length > 0 && <p>필요 계정: {intelligence.requiredAccounts.join(", ")}</p>}{intelligence.userActions.length > 0 && <p>사용자 작업: {intelligence.userActions.join(", ")}</p>}</div></div>; }
function ArchitectureSummary({ architecture }: { architecture: NonNullable<Snapshot["architecture"]> }) { return <div className="mt-5 border border-violet-400/20 bg-violet-400/5 p-5"><p className="text-xs uppercase tracking-[0.2em] text-violet-300">Architecture Snapshot</p><p className="mt-3 text-sm text-zinc-300">{architecture.summary}</p><div className="mt-4 flex flex-wrap gap-2">{architecture.components.map((component) => <span key={component.id} className="border border-zinc-700 px-2 py-1 text-xs text-zinc-300">{component.name}</span>)}</div><p className="mt-4 text-xs text-zinc-500">{architecture.connections.length}개 연결 · {architecture.components.length}개 Component</p></div>; }
