import type { ArchitectureSnapshot, BuildIntelligence, Requirement } from "../requirements/types";
import { calculateBuildIntelligence } from "../requirements/intelligence";
import { calculateCapabilitySummary, calculateCapabilities } from "../requirements/constraints";
import { getConsentRequirements } from "../requirements/consent";
import { selectArchitecture } from "./selector";
import { componentRegistry } from "./registry";
import { normalizeBuildPreference, type BuildPreference, type CostPreference } from "../preferences/types";

export type CandidateStatus = "AVAILABLE" | "SELECTED" | "OUT_OF_BUDGET";
export type CandidateMetrics = Pick<BuildIntelligence, "estimatedMonthlyCostCents" | "estimatedSetupMinutes" | "estimatedBuildMinutes" | "automation" | "riskScore" | "confidence" | "difficulty"> & { initialCostCents: number; userActionCount: number; expertActionCount: number };
export type ArchitectureCandidate = { id: string; strategy: CostPreference; architecture: ArchitectureSnapshot; metrics: CandidateMetrics; advantages: string[]; cautions: string[]; status: CandidateStatus };
export type ArchitectureCandidates = { version: "architecture-candidates-v1"; candidates: ArchitectureCandidate[]; selectedCandidateId: string | null };

function strategyRequirement(requirement: Requirement, strategy: CostPreference): Requirement { return { ...requirement, automationLevel: strategy === "FREE_FIRST" ? "guide" : strategy === "PERFORMANCE_FIRST" ? "high" : requirement.automationLevel }; }
function buildCandidate(requirement: Requirement, preference: BuildPreference, strategy: CostPreference): ArchitectureCandidate { const architecture = selectArchitecture(strategyRequirement(requirement, strategy)); const performanceAutomation = componentRegistry.find((component) => component.id === "n8n"); const performanceArchitecture = strategy === "PERFORMANCE_FIRST" && performanceAutomation && !architecture.components.some((component) => component.id === "n8n") ? { ...architecture, components: [...architecture.components, performanceAutomation], connections: [...architecture.connections, { from: "openai", to: "n8n", label: "Workflow 실행" }] } : architecture; const filtered = strategy === "FREE_FIRST" ? { ...architecture, components: architecture.components.filter((component) => !preference.excludedTools.includes(component.id) && !["n8n", "slack"].includes(component.id)), connections: architecture.connections.filter((connection) => !["n8n", "slack"].includes(connection.to)) } : performanceArchitecture; const capabilities = calculateCapabilities(requirement, getConsentRequirements(requirement).length); const intelligence = calculateBuildIntelligence(requirement, filtered, calculateCapabilitySummary(capabilities), getConsentRequirements(requirement), 70); const metrics = { estimatedMonthlyCostCents: intelligence.estimatedMonthlyCostCents + (strategy === "FREE_FIRST" ? 0 : strategy === "PERFORMANCE_FIRST" ? 5000 : 1500), estimatedSetupMinutes: intelligence.estimatedSetupMinutes, estimatedBuildMinutes: intelligence.estimatedBuildMinutes, automation: strategy === "FREE_FIRST" ? Math.min(intelligence.automation, 65) : strategy === "PERFORMANCE_FIRST" ? Math.max(intelligence.automation, 90) : Math.max(intelligence.automation, 75), riskScore: intelligence.riskScore, confidence: intelligence.confidence, difficulty: intelligence.difficulty, initialCostCents: strategy === "FREE_FIRST" ? 0 : strategy === "PERFORMANCE_FIRST" ? 5000 : 1500, userActionCount: strategy === "FREE_FIRST" ? 5 : strategy === "PERFORMANCE_FIRST" ? 1 : 3, expertActionCount: strategy === "PERFORMANCE_FIRST" ? 1 : 0 }; return { id: `candidate-${strategy.toLowerCase()}`, strategy, architecture: filtered, metrics, advantages: strategy === "FREE_FIRST" ? ["초기 비용 절감", "무료 티어 우선"] : strategy === "PERFORMANCE_FIRST" ? ["높은 자동화", "확장성과 품질 우선"] : ["비용과 편의성의 균형"], cautions: strategy === "FREE_FIRST" ? ["사용자 설정 작업이 많을 수 있음"] : strategy === "PERFORMANCE_FIRST" ? ["운영비가 높을 수 있음"] : ["일부 유료 서비스가 포함될 수 있음"], status: "AVAILABLE" }; }
export function generateArchitectureCandidates(requirement: Requirement, input: Partial<BuildPreference> = {}): ArchitectureCandidates { const preference = normalizeBuildPreference(input); const strategies: CostPreference[] = ["FREE_FIRST", "BALANCED", "PERFORMANCE_FIRST"]; const candidates = strategies.map((strategy) => buildCandidate(requirement, preference, strategy)); const budget = preference.monthlyBudgetLimit; const eligible = preference.costPreference === "CUSTOM_BUDGET" && budget !== null ? candidates.filter((candidate) => candidate.metrics.estimatedMonthlyCostCents <= budget * 100) : candidates; return { version: "architecture-candidates-v1", candidates: candidates.map((candidate) => eligible.some((item) => item.id === candidate.id) ? candidate : { ...candidate, status: "OUT_OF_BUDGET" }), selectedCandidateId: null }; }
export function selectArchitectureCandidate(candidates: ArchitectureCandidates, candidateId: string): ArchitectureCandidate | null { const selected = candidates.candidates.find((candidate) => candidate.id === candidateId && candidate.status !== "OUT_OF_BUDGET"); return selected ? { ...selected, status: "SELECTED" } : null; }
