import { useState } from "react";
import type { Bf0RequirementCandidate, Bf0RequirementKind, Bf0RequirementSupport } from "../bf0-view-model";

const supportClass: Record<Bf0RequirementSupport, string> = {
  "표준 선택으로 표현 가능": "border-cyan-200/25 bg-cyan-200/5 text-cyan-100",
  "구축 가이드 가능": "border-violet-200/25 bg-violet-200/5 text-violet-100",
  "추가 연결 필요": "border-amber-200/25 bg-amber-200/5 text-amber-100",
  "별도 도구 선택 필요": "border-rose-200/25 bg-rose-200/5 text-rose-100",
  "기준 추가 확인 필요": "border-orange-200/25 bg-orange-200/5 text-orange-100",
  "현재 템플릿으로 표현 어려움": "border-rose-200/25 bg-rose-200/5 text-rose-100",
};

const kindLabels: Array<{ value: Bf0RequirementKind; label: string }> = [
  { value: "trigger", label: "시작 조건" }, { value: "source", label: "입력 데이터" }, { value: "action", label: "해야 할 일" }, { value: "condition", label: "판단 조건" }, { value: "destination", label: "결과 위치" }, { value: "constraint", label: "금지 조건" }, { value: "schedule", label: "일정" }, { value: "unknown", label: "기타 요구" },
];

export function Bf0RequirementEditor({ requirements, gaps, onUpdate, onRemove, onAdd }: { requirements: Bf0RequirementCandidate[]; gaps: Bf0RequirementCandidate[]; onUpdate: (id: string, value: string) => void; onRemove: (id: string) => void; onAdd: (kind: Bf0RequirementKind, value: string) => void }) {
  const [kind, setKind] = useState<Bf0RequirementKind>("unknown");
  const [value, setValue] = useState("");
  const add = () => { const trimmed = value.trim(); if (!trimmed) return; onAdd(kind, trimmed); setValue(""); };
  return <section className="mt-6 rounded-3xl border border-slate-800 bg-slate-950/75 p-5 sm:p-6" aria-labelledby="bf0-understood-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-medium tracking-[0.22em] text-cyan-200">RULE-BASED INITIAL INTERPRETATION</p><h2 id="bf0-understood-title" className="mt-2 text-xl font-semibold text-white">BuildFlow가 이해한 내용</h2></div><span className="rounded-full border border-slate-700 px-3 py-1.5 text-xs text-slate-400">사용자가 확인하고 수정해야 합니다</span></div><p className="mt-3 text-sm leading-6 text-slate-400">입력에서 다음 요구사항 후보를 찾았습니다. 실제 연결·분석·검증 결과가 아닙니다.</p><div className="mt-5 grid gap-3">{requirements.map((requirement) => <RequirementRow key={requirement.id} requirement={requirement} onUpdate={onUpdate} onRemove={onRemove} />)}</div>{gaps.length > 0 && <section className="mt-5 rounded-2xl border border-amber-200/20 bg-amber-200/5 p-4" role="status"><h3 className="text-sm font-medium text-amber-100">확인이 필요한 항목이 있습니다</h3><ul className="mt-2 grid gap-1 text-sm leading-6 text-slate-300">{gaps.map((gap) => <li key={gap.id}>• {gap.value} — {gap.support}</li>)}</ul></section>}<div className="mt-5 border-t border-slate-800 pt-5"><h3 className="text-sm font-medium text-white">직접 항목 추가</h3><div className="mt-3 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="bf0-requirement-kind">요구사항 종류</label><select id="bf0-requirement-kind" value={kind} onChange={(event) => setKind(event.target.value as Bf0RequirementKind)} className="min-h-[44px] rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm text-slate-100 focus:border-cyan-200 focus:outline-none">{kindLabels.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><label className="sr-only" htmlFor="bf0-requirement-add">추가할 요구사항</label><input id="bf0-requirement-add" value={value} onChange={(event) => setValue(event.target.value)} maxLength={240} placeholder="예: 금요일 오후에 요약 받기" className="min-h-[44px] min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-3 text-sm text-slate-100 outline-none focus:border-cyan-200" /><button type="button" onClick={add} disabled={!value.trim()} className="min-h-[44px] rounded-xl border border-cyan-200/40 px-4 text-sm font-medium text-cyan-100 disabled:cursor-not-allowed disabled:border-slate-700 disabled:text-slate-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-200">항목 추가</button></div></div></section>;
}

function RequirementRow({ requirement, onUpdate, onRemove }: { requirement: Bf0RequirementCandidate; onUpdate: (id: string, value: string) => void; onRemove: (id: string) => void }) {
  const [editing, setEditing] = useState(false);
  const [value, setValue] = useState(requirement.value);
  const save = () => { const trimmed = value.trim(); if (!trimmed) return; onUpdate(requirement.id, trimmed); setEditing(false); };
  return <article className="rounded-2xl border border-slate-800 bg-slate-900/45 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="text-xs text-slate-500">{requirement.label}</p>{editing ? <><label className="sr-only" htmlFor={`bf0-requirement-${requirement.id}`}>{requirement.label} 수정</label><input id={`bf0-requirement-${requirement.id}`} value={value} onChange={(event) => setValue(event.target.value)} aria-describedby={`bf0-requirement-support-${requirement.id}`} className="mt-2 min-h-[44px] w-full rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm text-slate-100 outline-none focus:border-cyan-200" /><button type="button" onClick={save} className="mt-2 min-h-[44px] rounded-xl border border-cyan-200/40 px-3 text-sm text-cyan-100">수정 저장</button></> : <p className="mt-1 break-words text-sm font-medium leading-6 text-slate-100">{requirement.value}</p>}<p id={`bf0-requirement-support-${requirement.id}`} className={`mt-3 inline-flex rounded-full border px-2.5 py-1 text-xs ${supportClass[requirement.support]}`}>{requirement.support}</p></div><div className="flex gap-1"><button type="button" onClick={() => { setValue(requirement.value); setEditing((current) => !current); }} aria-label={`${requirement.label} 내용 수정`} className="min-h-[44px] rounded-xl px-3 text-sm text-slate-300 hover:text-cyan-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-200">수정</button><button type="button" onClick={() => onRemove(requirement.id)} aria-label={`${requirement.label} 항목 삭제`} className="min-h-[44px] rounded-xl px-3 text-sm text-slate-400 hover:text-rose-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-rose-200">삭제</button></div></div></article>;
}
