import type { ReactNode } from "react";
import { BF0_DESIGN_STEPS, type Bf0Route } from "../bf0-view-model";

export function Bf0Brand({ compact = false }: { compact?: boolean }) {
  return <div className={`inline-flex items-center gap-2 font-semibold tracking-[0.24em] text-cyan-100 ${compact ? "text-xs" : "text-sm"}`}><span aria-hidden="true" className={`grid place-items-center rounded-xl border border-cyan-200/40 bg-cyan-300/10 text-cyan-100 ${compact ? "size-8 text-base" : "size-9 text-lg"}`}>B</span>BUILDFLOW</div>;
}

export function Bf0ProgressHeader({ route, onBack }: { route: Bf0Route; onBack: () => void }) {
  const currentIndex = Math.max(0, BF0_DESIGN_STEPS.findIndex((step) => step.route === route));
  const width = `${((currentIndex + 1) / BF0_DESIGN_STEPS.length) * 100}%`;
  return <header className="border-b border-slate-800/90 bg-[#050812]/90 px-5 py-5 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><button type="button" onClick={onBack} className="min-h-[44px] rounded-xl px-3 text-sm text-slate-400 hover:text-cyan-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-200">← 이전</button><Bf0Brand /><span className="rounded-full border border-slate-700 bg-slate-950/70 px-3 py-2 text-xs text-slate-400">이번 세션에만 유지</span></div><div className="mx-auto mt-5 max-w-6xl"><div className="flex items-center gap-4"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-cyan-200 via-sky-300 to-violet-300 transition-[width] duration-300 motion-reduce:transition-none" style={{ width }} /></div><p className="shrink-0 text-sm font-medium text-cyan-100">{currentIndex + 1} / {BF0_DESIGN_STEPS.length}</p></div><ol className="mt-3 hidden justify-between text-[11px] text-slate-500 sm:flex">{BF0_DESIGN_STEPS.map((step, index) => <li key={step.route} aria-current={route === step.route ? "step" : undefined} className={index === currentIndex ? "font-medium text-cyan-100" : undefined}>{index + 1}. {step.label}</li>)}</ol></div></header>;
}

export function Bf0ActionFooter({ backLabel, nextLabel, disabled = false, onBack, onNext, children }: { backLabel: string; nextLabel: string; disabled?: boolean; onBack: () => void; onNext: () => void; children?: ReactNode }) {
  return <footer className="sticky bottom-0 z-10 mx-auto mt-10 flex w-full max-w-[920px] items-center justify-between gap-4 border-t border-slate-800 bg-[#050812]/95 py-4 backdrop-blur"><button type="button" onClick={onBack} className="min-h-[48px] rounded-xl px-4 text-sm text-slate-300 hover:text-cyan-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-200">← {backLabel}</button>{children}<button type="button" disabled={disabled} onClick={onNext} className="min-h-[48px] rounded-xl border border-cyan-100/50 bg-gradient-to-r from-cyan-300/20 to-violet-300/25 px-5 text-sm font-semibold text-cyan-50 shadow-[0_8px_28px_rgba(99,102,241,.12)] hover:from-cyan-300/30 hover:to-violet-300/35 disabled:cursor-not-allowed disabled:border-slate-700 disabled:bg-slate-900 disabled:text-slate-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-200">{nextLabel} <span aria-hidden="true">→</span></button></footer>;
}
