import { describe, expect, it } from "vitest";
import type { LiveUserIdentityProvider } from "./identity";
import { deriveLiveUserIdentity } from "./identity";
import { runApprovedSlackDigestWrite } from "./live-recipe-service";

describe("LIVE-RECIPE-AI-NEWS-001 guarded C3 controlled live gate", () => {
  it.skipIf(process.env.BUILDFLOW_LIVE_SLACK_DIGEST_WRITE !== "1")(
    "Gate C3 runs one approved AI news digest write through the guarded BuildFlow service path",
    async () => {
      const testUserId = process.env.BUILDFLOW_LIVE_TEST_USER_ID;
      const channelId = process.env.BUILDFLOW_LIVE_SLACK_CHANNEL_ID;
      if (!testUserId || !channelId) throw new Error("BUILDFLOW_LIVE_TEST_USER_ID and BUILDFLOW_LIVE_SLACK_CHANNEL_ID are required for this gate");

      const identityProvider: LiveUserIdentityProvider = { resolve: async () => ({ ok: true, value: deriveLiveUserIdentity(testUserId) }) };

      const result = await runApprovedSlackDigestWrite(
        {
          approved: true,
          recipeId: "recipe.ai-news-slack-digest",
          targetConfigurationReference: channelId,
          requestId: `slack-digest-guarded-c3-verify-${Date.now()}`,
          message: "[BuildFlow AI 뉴스 테스트]\n\nGuarded C3 경로(runApprovedSlackDigestWrite) 실검증\n\nSource: OpenAI News\nGenerated by BuildFlow",
        },
        { identityProvider },
      );

      console.info(JSON.stringify({
        ok: result.ok,
        connectionState: result.connectionState,
        evidence: result.evidence,
        ...(result.ok ? {} : { errorCode: result.errorCode }),
      }));

      expect(result).toMatchObject({
        ok: true,
        connectionState: "CONNECTED_VERIFIED",
        evidence: { actionType: "AI_NEWS_DIGEST", status: "SUCCEEDED" },
      });
    },
  );
});
