"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { initialMetrics, nextState } from "./state-machine";
import type { ActionBundle, ApprovalPlan, AutonomousSession } from "./types";
async function owned(projectId: string) { const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return null; const { data: project } = await supabase.from("projects").select("id,goal_constraints").eq("id", projectId).eq("user_id", user.id).maybeSingle(); return project ? { supabase, user, project } : null; }
export async function getAutonomousBuildSession(projectId: string) { const access = await owned(projectId); if (!access) return null; const { data } = await access.supabase.from("autonomous_build_sessions").select("id,status").eq("project_id", projectId).eq("user_id", access.user.id).order("updated_at", { ascending: false }).limit(1).maybeSingle(); return data; }
function bundle(snapshot: Record<string, unknown>): ActionBundle { const connectors = Array.isArray(snapshot.connectors) ? snapshot.connectors as Array<{ providerId?: string; required?: boolean }> : []; const required = connectors.filter((item) => item.required).map((item) => ({ id: `credential-${item.providerId}`, label: `${item.providerId} Credential 연결`, required: true, kind: "CREDENTIAL" as const, estimatedMinutes: 5, estimatedCostCents: 0, autoResume: true })); return { required, optional: [], totalEstimatedMinutes: required.length * 5, totalEstimatedCostCents: 0, autoResume: true }; }
function approval(snapshot: Record<string, unknown>): ApprovalPlan { const architecture = snapshot.selectedArchitectureSnapshot as { components?: Array<{ name?: string; monthlyCostCents?: number; required?: boolean }> } | undefined; const components = architecture?.components ?? []; return { resources: components.filter((item) => item.required).map((item) => item.name ?? "resource"), estimatedCostCents: components.reduce((sum, item) => sum + (item.monthlyCostCents ?? 0), 0), permissionChanges: [], publicDeployment: false, reversible: true, scopeVersion: "approval-plan-v1" }; }
export async function startAutonomousBuildSession(projectId: string) { const access = await owned(projectId); if (!access) return { ok: false as const, error: "NOT_AUTHORIZED" }; const constraints = (access.project.goal_constraints ?? {}) as Record<string, unknown>; const snapshot = (constraints.requirement_snapshot ?? {}) as Record<string, unknown>; if (!snapshot.requirement || !snapshot.selectedArchitectureSnapshot || !snapshot.buildPlan) return { ok: false as const, error: "BUILD_INPUT_INCOMPLETE" }; const actionBundle = bundle(snapshot); const approvalPlan = approval(snapshot); const status = actionBundle.required.length ? "WAITING_FOR_CREDENTIAL" : approvalPlan.estimatedCostCents ? "WAITING_FOR_APPROVAL" : "PLANNING"; const { data, error } = await access.supabase.from("autonomous_build_sessions").insert({ project_id: projectId, user_id: access.user.id, status, current_phase: status === "WAITING_FOR_CREDENTIAL" ? "PREPARATION" : status === "WAITING_FOR_APPROVAL" ? "APPROVAL" : "PLANNING", action_bundle: actionBundle as never, approval_plan: approvalPlan as never, metrics: initialMetrics() as never }).select("id").single(); if (error || !data) return { ok: false as const, error: "SESSION_CREATE_FAILED" }; revalidatePath(`/app/projects/${projectId}`); return { ok: true as const, sessionId: data.id, status }; }
export async function resumeAutonomousBuildSession(projectId: string, sessionId: string, event: Parameters<typeof nextState>[1]) { const access = await owned(projectId); if (!access) return { ok: false as const, error: "NOT_AUTHORIZED" }; const { data } = await access.supabase.from("autonomous_build_sessions").select("*").eq("id", sessionId).eq("project_id", projectId).maybeSingle(); if (!data) return { ok: false as const, error: "SESSION_NOT_FOUND" }; const current = { id: data.id, projectId: data.project_id, userId: data.user_id, status: data.status, currentPhase: data.current_phase, completedPhases: data.completed_phases, blockedReason: data.blocked_reason ?? undefined, actionBundle: data.action_bundle, approvalPlan: data.approval_plan, metrics: data.metrics, executionId: data.execution_id ?? undefined } as AutonomousSession; const updated = nextState(current, event); const { error } = await access.supabase.from("autonomous_build_sessions").update({ status: updated.status, current_phase: updated.currentPhase, completed_phases: updated.completedPhases as never, metrics: updated.metrics as never }).eq("id", sessionId).eq("project_id", projectId); if (error) return { ok: false as const, error: "SESSION_UPDATE_FAILED" }; revalidatePath(`/app/projects/${projectId}`); return { ok: true as const, status: updated.status }; }
