import { calculateClarificationSummary, getClarificationQuestions } from "./clarification";
import { assessConstraints } from "./constraints";
import { getConsentRequirements } from "./consent";
import { parseGoal } from "./goal-parser";
import { calculateCapabilities, calculateCapabilitySummary } from "./constraints";
import { createConversation } from "./conversation";
import { calculateBuildIntelligence } from "./intelligence";
import type { RequirementSnapshot } from "./types";
import { generateBuildPlan } from "../planner/generator";
import { createInstallationSession } from "../installation/session";
import { createTestSuite } from "../testing/engine";
import { resolveRequiredConnectors } from "../connectors/resolver";
import { createAccountConnectionSession } from "../connectors/oauth";
import { createCredentialReferences } from "../credentials/references";
import { generateArchitectureCandidates } from "../architecture/candidates";
import { normalizeBuildPreference } from "../preferences/types";
export function createRequirementSnapshot(goal: string, constraints: { automation_level?: string; budget_range?: string; current_tools?: string[]; cost_preference?: "FREE_FIRST" | "BALANCED" | "PERFORMANCE_FIRST" | "CUSTOM_BUDGET"; automation_preference?: "GUIDED" | "PARTIAL_AUTOMATION" | "FULL_AUTOMATION"; monthly_budget_limit?: number | null; preferred_tools?: string[]; excluded_tools?: string[] } = {}): RequirementSnapshot { const preference = normalizeBuildPreference({ ...constraints, costPreference: constraints.cost_preference, automationPreference: constraints.automation_preference, monthlyBudgetLimit: constraints.monthly_budget_limit, preferredTools: constraints.preferred_tools, excludedTools: constraints.excluded_tools }); const requirement = parseGoal(goal, constraints); const candidates = generateArchitectureCandidates(requirement, preference); const selected = candidates.candidates.find((candidate) => candidate.strategy === (preference.costPreference === "CUSTOM_BUDGET" ? "BALANCED" : preference.costPreference)) ?? candidates.candidates[1]; const architecture = selected.architecture; const consents = getConsentRequirements(requirement); const clarificationQuestions = getClarificationQuestions(requirement); const clarificationSummary = calculateClarificationSummary(clarificationQuestions); const capabilities = calculateCapabilities(requirement, consents.length); const capabilitySummary = calculateCapabilitySummary(capabilities); const connectors = resolveRequiredConnectors(requirement, architecture); const credentialReferences = createCredentialReferences(connectors); const connectorsWithReferences = connectors.map((connector) => ({ ...connector, credentialReference: credentialReferences.find((reference) => reference.providerId === connector.providerId) })); const accountConnection = createAccountConnectionSession(connectorsWithReferences); const buildIntelligence = calculateBuildIntelligence(requirement, architecture, capabilitySummary, consents, clarificationSummary.buildReadiness); const buildPlan = generateBuildPlan({ requirement, architecture, intelligence: buildIntelligence }); const installation = createInstallationSession(buildPlan); return { requirement, buildPreference: preference, architectureCandidates: candidates, selectedCandidateId: selected.id, clarificationQuestions, clarificationSummary, conversation: createConversation(requirement, clarificationQuestions, clarificationSummary.buildReadiness), constraints: assessConstraints(requirement), capabilities, capabilitySummary, consents, architecture, connectors: connectorsWithReferences, credentialReferences, accountConnection, buildIntelligence, buildPlan, installation, testSuite: createTestSuite({ architecture, buildPlan, installation }) }; }
