export type GoalType = "customer_support" | "content_creation" | "data_analysis" | "communication" | "productivity" | "unknown";
export type ConstraintLevel = "AUTO" | "PARTIAL" | "CONSENT_REQUIRED" | "MANUAL" | "EXPERT" | "UNSUPPORTED";
export type AutomationLevel = ConstraintLevel;
export type Requirement = { version: "requirement-v1"; goalOriginal: string; goalType: GoalType; category: string; expectedOutput: string; businessGoal: string; primaryUser: string | null; automationLevel: string; budget: string; deadline: string | null; currentTools: string[]; restrictions: string[]; requiredIntegrations: string[] };
export type ClarificationQuestion = { id: string; question: string; field: keyof Requirement | "platform" | "user_volume"; required: boolean; priority: number };
export type ConstraintAssessment = { level: ConstraintLevel; reason: string; requiresUserAction: boolean };
export type ConsentRequirement = { id: string; subject: string; reason: string; status: "required" | "not_required" | "pending" };
export type Capability = { id: string; label: string; level: AutomationLevel; reason: string; requiresConsent: boolean };
export type CapabilitySummary = { total: number; automation: number; partial: number; consent: number; manual: number; expert: number; unsupported: number };
export type ClarificationSummary = { completeness: number; buildReadiness: number; answered: number; total: number };
export type ConversationState = "WAITING" | "ASKING" | "COMPLETE" | "READY_FOR_BUILD";
export type ConversationSummary = { understood: string[]; missing: string[]; nextQuestion: ClarificationQuestion | null };
export type Conversation = { state: ConversationState; queue: ClarificationQuestion[]; missing: string[]; summary: ConversationSummary };
export type BuildIntelligence = { buildScore: number; automation: number; consent: number; manual: number; expert: number; unsupported: number; estimatedBuildMinutes: number; estimatedSetupMinutes: number; estimatedMonthlyCostCents: number; difficulty: "easy" | "moderate" | "hard"; riskScore: number; confidence: number; requiredAccounts: string[]; userActions: string[]; summary: string };
export type ComponentCategory = "frontend" | "llm" | "database" | "automation" | "notification" | "auth" | "storage" | "deployment";
export type ArchitectureComponent = { id: string; name: string; category: ComponentCategory; reason: string; required: boolean; setupMinutes?: number; monthlyCostCents?: number; riskWeight?: number };
export type ArchitectureConnection = { from: string; to: string; label: string };
export type ArchitectureDependency = { componentId: string; dependsOn: string[] };
export type ArchitectureSnapshot = { version: "architecture-v1"; components: ArchitectureComponent[]; connections: ArchitectureConnection[]; dependencies: ArchitectureDependency[]; summary: string };
export type RequirementSnapshot = { requirement: Requirement; clarificationQuestions: ClarificationQuestion[]; clarificationSummary: ClarificationSummary; conversation: Conversation; constraints: ConstraintAssessment[]; capabilities: Capability[]; capabilitySummary: CapabilitySummary; consents: ConsentRequirement[]; architecture: ArchitectureSnapshot; buildIntelligence: BuildIntelligence; buildPlan: BuildPlan; installation: InstallationSession; testSuite: TestSuite };
import type { TestSuite } from "../testing/types";
import type { BuildPlan } from "../planner/types";
import type { InstallationSession } from "../installation/types";
