import { serviceDefinitionSchema, type ServiceDefinition, type SourceReference } from "./types";

const collectedAt = "2026-08-14";

function official(sourceUrl: string, sourceTitle: string, organization: string): SourceReference {
  return { sourceType: "OFFICIAL_DOCUMENTATION", sourceUrl, sourceTitle, organization, license: "Reference documentation", usageRightsStatus: "REFERENCE_ONLY", collectedAt, lastVerifiedAt: collectedAt };
}

const services: ServiceDefinition[] = [
  { id: "rss", title: "RSS / News Source", category: "research", capabilities: [{ id: "feed.read", label: "RSS feed read", externalProcessing: true, externalWrite: false }], connectionRequirements: [], sourceReferences: [official("https://www.rssboard.org/rss-specification", "RSS 2.0 Specification", "RSS Advisory Board")], licenseNote: "Feed-specific terms apply." },
  { id: "slack", title: "Slack", category: "messaging", capabilities: [{ id: "message.send", label: "Send channel message", externalProcessing: true, externalWrite: true }, { id: "channel.trigger", label: "Channel trigger", externalProcessing: true, externalWrite: false }], connectionRequirements: [{ serviceId: "slack", mode: "OAUTH", required: true, userAction: "Connect the Slack workspace and choose a channel.", storesCredential: false }], sourceReferences: [official("https://api.slack.com/messaging", "Slack messaging API", "Slack")], licenseNote: "Official API reference only; no workflow export is copied." },
  { id: "groq", title: "Groq", category: "llm", capabilities: [{ id: "llm.completion", label: "LLM completion", externalProcessing: true, externalWrite: false }], connectionRequirements: [{ serviceId: "groq", mode: "API_KEY", required: true, userAction: "Provide a Groq connection in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://console.groq.com/docs/overview", "Groq API documentation", "Groq")], licenseNote: "API use requires a separate approved connection." },
  { id: "openai", title: "OpenAI", category: "llm", capabilities: [{ id: "llm.completion", label: "LLM completion", externalProcessing: true, externalWrite: false }], connectionRequirements: [{ serviceId: "openai", mode: "API_KEY", required: true, userAction: "Provide an OpenAI connection in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://platform.openai.com/docs", "OpenAI API documentation", "OpenAI")], licenseNote: "API use requires a separate approved connection." },
  { id: "pipedream", title: "Pipedream", category: "automation", capabilities: [{ id: "workflow.execute", label: "Workflow execution candidate", externalProcessing: true, externalWrite: true }, { id: "managed.auth", label: "Managed auth candidate", externalProcessing: true, externalWrite: false }], connectionRequirements: [{ serviceId: "pipedream", mode: "MANAGED_AUTH_CANDIDATE", required: false, userAction: "Select Pipedream as the execution engine during a future build step.", storesCredential: false }], sourceReferences: [official("https://pipedream.com/docs/connect/workflows", "Pipedream Connect workflows", "Pipedream")], licenseNote: "Preview metadata only; live workflow creation is excluded." },
  { id: "make", title: "Make", category: "automation", capabilities: [{ id: "scenario.execute", label: "Scenario execution candidate", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "make", mode: "MANAGED_AUTH_CANDIDATE", required: false, userAction: "Select Make as the execution engine during a future build step.", storesCredential: false }], sourceReferences: [official("https://developers.make.com/api-documentation/api-reference/scenarios", "Make scenarios API", "Make")], licenseNote: "Preview metadata only; live scenario creation is excluded." },
  { id: "activepieces", title: "Activepieces", category: "automation", capabilities: [{ id: "flow.execute", label: "Flow execution candidate", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "activepieces", mode: "MANAGED_AUTH_CANDIDATE", required: false, userAction: "Select Activepieces as the execution engine during a future build step.", storesCredential: false }], sourceReferences: [official("https://www.activepieces.com/docs/about/license", "Activepieces license", "Activepieces")], licenseNote: "Preview metadata only; deployment is excluded." },
  { id: "n8n", title: "n8n", category: "automation", capabilities: [{ id: "workflow.execute", label: "Workflow execution candidate", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "n8n", mode: "MANAGED_AUTH_CANDIDATE", required: false, userAction: "Review n8n licensing and select it only in an approved build flow.", storesCredential: false }], sourceReferences: [official("https://support.n8n.io/article/can-i-use-your-license-for-my-use-case", "n8n licensing guidance", "n8n")], licenseNote: "License-sensitive integration candidate; preview only." },
  { id: "gmail", title: "Gmail", category: "email", capabilities: [{ id: "email.read", label: "Read email", externalProcessing: true, externalWrite: false }, { id: "email.send", label: "Send email", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "gmail", mode: "OAUTH", required: true, userAction: "Connect the Google account in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://developers.google.com/gmail/api", "Gmail API", "Google")], licenseNote: "OAuth connection is not performed in this slice." },
  { id: "notion", title: "Notion", category: "knowledge", capabilities: [{ id: "page.create", label: "Create page", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "notion", mode: "OAUTH", required: true, userAction: "Connect the Notion workspace in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://developers.notion.com/", "Notion API", "Notion")], licenseNote: "OAuth connection is not performed in this slice." },
  { id: "google-sheets", title: "Google Sheets", category: "data", capabilities: [{ id: "sheet.append", label: "Append row", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "google-sheets", mode: "OAUTH", required: true, userAction: "Connect the Google account in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://developers.google.com/sheets/api", "Google Sheets API", "Google")], licenseNote: "OAuth connection is not performed in this slice." },
  { id: "google-drive", title: "Google Drive", category: "storage", capabilities: [{ id: "file.create", label: "Create document", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "google-drive", mode: "OAUTH", required: true, userAction: "Connect the Google account in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://developers.google.com/drive", "Google Drive API", "Google")], licenseNote: "OAuth connection is not performed in this slice." },
  { id: "google-calendar", title: "Google Calendar", category: "calendar", capabilities: [{ id: "calendar.event", label: "Calendar event trigger", externalProcessing: true, externalWrite: false }], connectionRequirements: [{ serviceId: "google-calendar", mode: "OAUTH", required: true, userAction: "Connect the Google account in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://developers.google.com/calendar/api", "Google Calendar API", "Google")], licenseNote: "OAuth connection is not performed in this slice." },
  { id: "shopify", title: "Shopify", category: "commerce", capabilities: [{ id: "order.read", label: "Read orders", externalProcessing: true, externalWrite: false }, { id: "customer.update", label: "Update customer", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "shopify", mode: "OAUTH", required: true, userAction: "Connect the Shopify store in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://shopify.dev/docs/api", "Shopify API", "Shopify")], licenseNote: "OAuth connection is not performed in this slice." },
  { id: "hubspot", title: "HubSpot", category: "crm", capabilities: [{ id: "contact.create", label: "Create or update contact", externalProcessing: true, externalWrite: true }], connectionRequirements: [{ serviceId: "hubspot", mode: "OAUTH", required: true, userAction: "Connect the HubSpot account in a future approved connection flow.", storesCredential: false }], sourceReferences: [official("https://developers.hubspot.com/docs/api/overview", "HubSpot API", "HubSpot")], licenseNote: "OAuth connection is not performed in this slice." },
];

export const serviceRegistry = services.map((service) => serviceDefinitionSchema.parse(service));
export function findService(id: string) { return serviceRegistry.find((service) => service.id === id); }
