"use client";

import { useActionState } from "react";
import type { ProjectFormState } from "@/features/projects/types";

const emptyState: ProjectFormState = {};
export function ProjectForm({ action, project }: { action: (state: ProjectFormState, formData: FormData) => Promise<ProjectFormState>; project?: { id: string; title: string; goal: string | null; goal_description: string | null; goal_constraints: unknown } }) {
  const [state, formAction, pending] = useActionState(action, emptyState);
  const constraints = (project?.goal_constraints ?? {}) as Record<string, string | string[]>;
  const tools = Array.isArray(constraints.current_tools) ? constraints.current_tools.join(", ") : String(constraints.current_tools ?? "");
  return <form action={formAction} className="space-y-6">{project && <input type="hidden" name="projectId" value={project.id} />}{state.error && <p role="alert" className="border border-red-400/30 bg-red-400/10 px-3 py-2 text-sm text-red-200">{state.error}</p>}<Field label="프로젝트 이름" name="title" error={state.fieldErrors?.title} defaultValue={project?.title} placeholder="고객 문의 자동 분류" /><Field label="무엇을 만들고 싶나요?" name="goal" error={state.fieldErrors?.goal} defaultValue={project?.goal ?? ""} placeholder="고객 문의 이메일을 유형별로 분류하고 답변 초안을 만들고 싶어요." textarea /><Field label="추가 설명" name="description" error={state.fieldErrors?.description} defaultValue={project?.goal_description ?? ""} placeholder="현재 상황이나 원하는 결과를 더 알려주세요." textarea />
    <Select label="AI 숙련도" name="ai_skill_level" defaultValue={String(constraints.ai_skill_level ?? "beginner")} options={[["beginner", "처음 사용"], ["intermediate", "조금 사용해 봄"], ["advanced", "익숙함"]]} /><Select label="개발 가능 여부" name="can_code" defaultValue={String(constraints.can_code ?? "false")} options={[["false", "개발할 수 없음"], ["true", "직접 개발 가능"]]} /><Select label="예산" name="budget_range" defaultValue={String(constraints.budget_range ?? "unknown")} options={[["free", "무료 우선"], ["low", "낮음"], ["medium", "중간"], ["high", "높음"], ["unknown", "잘 모르겠음"]]} /><Select label="자동화 수준" name="automation_level" defaultValue={String(constraints.automation_level ?? "unknown")} options={[["guide", "가이드만 필요"], ["partial", "일부 자동화"], ["high", "높은 자동화"], ["unknown", "잘 모르겠음"]]} /><Field label="현재 사용 중인 도구" name="current_tools" error={state.fieldErrors?.current_tools} defaultValue={tools} placeholder="예: Gmail, Notion, Slack" /><button type="submit" disabled={pending} className="w-full border border-cyan-400/50 bg-cyan-400/10 px-4 py-3 text-sm font-medium text-cyan-200 disabled:cursor-wait disabled:opacity-50">{pending ? "프로젝트를 만들고 있습니다..." : project ? "프로젝트 저장" : "프로젝트 만들기"}</button></form>;
}
function Field({ label, name, error, textarea, ...props }: { label: string; name: string; error?: string; textarea?: boolean; defaultValue?: string; placeholder?: string }) { const input = textarea ? <textarea name={name} rows={4} {...props} className="w-full border border-zinc-700 bg-zinc-900 px-3 py-3 text-zinc-100 outline-none focus:border-cyan-400" /> : <input name={name} {...props} className="w-full border border-zinc-700 bg-zinc-900 px-3 py-3 text-zinc-100 outline-none focus:border-cyan-400" />; return <label className="block space-y-2 text-sm text-zinc-300">{label}{input}{error && <span className="text-xs text-red-300">{error}</span>}</label>; }
function Select({ label, name, options, defaultValue }: { label: string; name: string; options: string[][]; defaultValue: string }) { return <label className="block space-y-2 text-sm text-zinc-300">{label}<select name={name} defaultValue={defaultValue} className="w-full border border-zinc-700 bg-zinc-900 px-3 py-3 text-zinc-100 outline-none focus:border-cyan-400">{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>; }
